name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [development, master]
  push:
    branches:
      - development
      - feature/**
    tags: 
      - '**'

jobs:
  determine-environment:
    uses: TokioFinal/tokio_reusable_workflows/.github/workflows/determine_environment.yaml@v2

  test:
    uses: TokioFinal/tokio_reusable_workflows/.github/workflows/test_python_app.yaml@v2
  
  build-push:
    runs-on: ubuntu-latest
    needs: [ test, determine-environment ]
    environment: ${{needs.determine-environment.outputs.selected-environment}}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata
        shell: bash
        run: |
          echo "ref=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          echo "short_sha=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT
        id: extract_metadata
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY}}
          tags: |
            ${{steps.extract_metadata.outputs.ref}}
            ${{steps.extract_metadata.outputs.short_sha}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags:  ${{ steps.meta.outputs.tags }}
          file: ${{ vars.DOCKERFILE }}